version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source.
    tables:
      - name: finance_campaigns_day
        identifier : finance_campaigns_day.sql
        description: ads margin.
      - name: campaigns
        identifier : int_campaigns.sql
        description: KPI of campaigns of all channel regroupped.
       
      - name: int_campaigns_day.sql
        identifier : int_campaigns_day.sql
        description: aggregated version of int_campaigns model for each day.
        

      - name: adwords
        identifier : raw_gz_adwords
        description: cost, impressions and click per campaign and per day for adwords campaign.
        tests:
          - unique:
              column_name: "(date_date ||'-'||campaign_key)"
        columns: 
          - name : date_date
            description : date of the campaign.
            tests :
              - not_null
          - name : paid_source
            description : channel of campaign.
            tests :
              - not_null
          - name : campaign_key
            description : id of campaign.
            tests :
              - not_null
          - name : campaign_name
            description : campaign name.
            
          - name : ads_cost
            description : ads cost.
            tests :
              - not_null
          - name : impression
            description : number of impression par date and campaign.
          - name : click
            description : number of click par date and campaign.
            
      - name : bing
        identifier : raw_gz_bing
        description: cost, impressions and click per campaign and per day for bing campaign.
        tests:
          - unique:
              column_name: "(date_date ||'-'||campaign_key)"
        columns: 
          - name : date_date
            description : date of the campaign.
            tests :
              - not_null
          - name : paid_source
            description : channel of campaign.
            tests :
              - not_null
          - name : campaign_key
            description : id of campaign.
            tests :
              - not_null
          - name : campaign_name
            description : campaign name.
            
          - name : ads_cost
            description : ads cost.
            tests :
              - not_null
          - name : impression
            description : number of impression par date and campaign.
          - name : click
            description : number of click par date and campaign.
            
      - name : criteo
        identifier : raw_gz_criteo
        description: cost, impressions and click per campaign and per day for criteo campaign.
        tests:
          - unique:
              column_name: "(date_date ||'-'||campaign_key)"
        columns: 
          - name : date_date
            description : date of the campaign.
            tests :
              - not_null
          - name : paid_source
            description : channel of campaign.
            tests :
              - not_null
          - name : campaign_key
            description : id of campaign.
            tests :
              - not_null
          - name : campaign_name
            description : campaign name.
            
          - name : ads_cost
            description : ads cost.
            tests :
              - not_null
          - name : impression
            description : number of impression par date and campaign.
          - name : click
            description : number of click par date and campaign.
            
      - name : facebook
        identifier : raw_gz_facebook
        description: cost, impressions and click per campaign and per day for facebook campaign.
        tests:
          - unique:
              column_name: "(date_date ||'-'||campaign_key)"
        columns: 
          - name : date_date
            description : date of the campaign.
            tests :
              - not_null
          - name : paid_source
            description : channel of campaign.
            tests :
              - not_null
          - name : campaign_key
            description : id of campaign.
            tests :
              - not_null
          - name : campaign_name
            description : campaign name.
            
          - name : ads_cost
            description : ads cost.
            tests :
              - not_null
          - name : impression
            description : number of impression par date and campaign.
          - name : click
            description : number of click par date and campaign.
            
      - name: product
        identifier: raw_gz_product
        description: purchase price per product / products_id is the primary key.
        columns:
          - name: products_id
            description: primary key.
            tests:
              - unique
              - not_null

          - name: purchase_price
            description: purchase price of each product.
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one 'raw' per pdt_id found in each orders_id.
        columns:
          - name: date_date
            description: date of the sale.
          - name: orders_id
            description: id of the order.
          - name: pdt_id
            description: id of the product.
          - name: revenue
            description: revenue of the product.
          - name: quantity
            description: quantity of product sold.
        tests:
          - unique:
              column_name: "(orders_id ||'-'||pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: shipping fee/ log cost and ship cost per orders_id / orders_id is the primary key.
        columns:
          - name: orders_id
            description: id of orders, primary key.
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee per order.
          - name: logcost
            description: cost of logistic per order.
          - name: ship_cost
            description: cost of ship per order.
      - name: int_sales_margin
        columns:
          - name: products_id
          - name: date_date
          - name: orders_id
          - name: revenue
          - name: quantity
          - name: purchase_price
          - name: margin
          - name: purchase_cost
